
alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      group_wait: 20s
      group_interval: 4m
      repeat_interval: 4h
      receiver: 'email-notifications'
    receivers:
      - name: 'email-notifications'
        email_configs:
          - to: 'adriaan.meulenbelt-zumer@efrei.net'
            from: 'email-k8s-admin@alertmanager.com'
            smarthost: 'smtp.gmail.com:587'
            auth_username: 'devopsgroupn4efrei@gmail.com'
            auth_password: 'scmb wmdm nnsg dwat'
            auth_identity: 'devopsgroupn4efrei@gmail.com'
            send_resolved: true