serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: 'my-app'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: my-app
        metrics_path: /metrics
        scheme: http
        static_configs:
            - targets:
                - my-app.default.svc.cluster.local:8080
