serverFiles:
  alerting_rules.yml:
    groups:
      - name: ApplicationTargets
        rules:
          - alert: MyAppDown
            expr: up == 0 OR absent(up{job="my-app"})
            for: 30s
            labels:
              severity: critical
            annotations:
              summary: "MyApp is down!"
              description: "Instance {{ $labels.instance }} of MyApp is down for more than 1 minute."
