apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project-dev
  labels:
    app: my-app
    environment: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
      environment: development
  template:
    metadata:
      labels:
        app: my-app
        environment: development
    spec:
      containers:
      - name: my-app
        image: your-dockerhub-username/your-image-name:latest
        imagePullPolicy: Always # Kubernetes tirera toujours l'image depuis Docker Hub
