apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
    environment: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
      environment: production
  template:
    metadata:
      labels:
        app: my-app
        environment: production
    spec:
      containers:
        - name: my-app
          image: devopsefreiproject/devops_project:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
      imagePullSecrets:
        - name: my-dockerhub-secret

---
apiVersion: v1
kind: Service
metadata:
  name: my-app
  namespace: default
  labels:
    environment: production
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
