apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project-prod
  labels:
    app: my-app
    environment: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
      environment: production
  template:
    metadata:
      labels:
        app: my-app
        environment: production
        monitoring: enabled
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: my-app
          image: devopsefreiproject/devops_project:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: "/metrics"
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: "/metrics"
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
      imagePullSecrets:
        - name: my-dockerhub-secret

---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  labels:
    app: my-app
    environment: production
    monitoring: enabled
spec:
    ports:
        - port: 8080
          targetPort: 8080
    selector:
        app: my-app
        environment: production
    type: LoadBalancer
